### ISSUE TITLE
Set Path as a name in attached filed

### ISSUE THREAD

**Issue by sam4444** [kristijandraca/BackgroundMailLibrary#12]
Please refer below link...

http://stackoverflow.com/questions/28273905/ioexception-while-sending-message-file-cant-attach

Well i attach a file. file is get path as a name. I can't find a solution  maybe this is from my side or in library..

Please see below screenshot for more clarifications...
https://mmi230.whatsapp.net/d/dNjvpGRIcWHGhN4KUJsz01TPOP0/Ak4vR0-TZgCeCPrnxwBgQ64iXTxg1JzLl_oej2lWGFka.jpg

**Comment by kristijandraca** [comment]
Please update links
