### ISSUE TITLE
AuthenticationFailedException

### ISSUE THREAD

**Issue by benjaminthorent** [kristijandraca/BackgroundMailLibrary#14]
03-24 00:40:18.763: W/System.err(13645): javax.mail.AuthenticationFailedException
03-24 00:40:18.763: W/System.err(13645): 	at javax.mail.Service.connect(Service.java:319)
03-24 00:40:18.763: W/System.err(13645): 	at javax.mail.Service.connect(Service.java:169)
03-24 00:40:18.763: W/System.err(13645): 	at javax.mail.Service.connect(Service.java:118)
03-24 00:40:18.763: W/System.err(13645): 	at javax.mail.Transport.send0(Transport.java:188)
03-24 00:40:18.763: W/System.err(13645): 	at javax.mail.Transport.send(Transport.java:118)
03-24 00:40:18.763: W/System.err(13645): 	at com.benfactory.killerapp.mail.mail.GmailSender.sendMail(GmailSender.java:76)
03-24 00:40:18.763: W/System.err(13645): 	at com.benfactory.killerapp.mail.BackgroundMail$startSendingEmail.doInBackground(BackgroundMail.java:119)
03-24 00:40:18.763: W/System.err(13645): 	at com.benfactory.killerapp.mail.BackgroundMail$startSendingEmail.doInBackground(BackgroundMail.java:1)
03-24 00:40:18.764: W/System.err(13645): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
03-24 00:40:18.764: W/System.err(13645): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-24 00:40:18.764: W/System.err(13645): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
03-24 00:40:18.764: W/System.err(13645): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-24 00:40:18.764: W/System.err(13645): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-24 00:40:18.764: W/System.err(13645): 	at java.lang.Thread.run(Thread.java:818)

Hello !
And first, thanks a lot for this library :) ! Yet I face the above issue... I saw the solution you proposed (change security access to less secure app with dedicated gmail account) but it did not work for me :(. Any idea of what could cause this ?
Thanks in advance for your time and help on this one.
Cheers,
Ben

**Comment by kristijandraca** [comment]
https://github.com/kristijandraca/BackgroundMailLibrary/issues/3#issuecomment-60357918
