### ISSUE TITLE
Error on Jitpack?

### ISSUE THREAD

**Issue by Spotik** [kristijandraca/BackgroundMailLibrary#18]
Hey there im getting this error:

"Error:A problem occurred configuring project ':app'.
> Artifact 'BackgroundMailLibrary.jar (com.github.kristijandraca:BackgroundMailLibrary:1.5)' not found.
  Searched in the following locations:
      https://jitpack.io/com/github/kristijandraca/BackgroundMailLibrary/1.5/BackgroundMailLibrary-1.5.jar"

**Comment by kristijandraca** [comment]
yes, i'm working on fix

**Comment by Spotik** [comment]
Oh thks for the quickly answer =)

**Comment by jitpack-io** [comment]
Hi @kristijandraca. If we can help in any way give us a shout:)

**Comment by ShivamDev31** [comment]
Any updates on this? I'm not able to setup your lib to use it. I want to use it urgently.
