### ISSUE TITLE
Gradle problem

### ISSUE THREAD

**Issue by Victorgf87** [kristijandraca/BackgroundMailLibrary#19]
When I add this project to my Gradle.build, I get these two errors:
Error:(7, 9) Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:7:9
Error:(7, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:7:9
	is also present at com.github.kristijandraca:BackgroundMailLibrary:1.5:13:9 value=(@drawable/ic_launcher)
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:5:5 to override

My build file contains
repositories {
    maven {
        url "https://jitpack.io"
    }
}
And
compile 'com.github.kristijandraca:BackgroundMailLibrary:1.5'

**Comment by Victorgf87** [comment]
Sorry, I didn't see that the fix was in the error message ^^'
Now the problem is 
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 2

**Comment by agustinaliagac** [comment]
Same problem here (Error:Execution failed for task ':app:dexDebug'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_45\bin\java.exe'' finished with non-zero exit value 2)

**Comment by kristijandraca** [comment]
Yes I know about that, I will try to fix it. You can use older version

**Comment by vipulbansal** [comment]
When I try to add backgroundmaillibrary as a module in my project I am getting gradle errors in maven

**Comment by ShivamDev31** [comment]
I'm not getting how to use it. Trying to us version 1.8. Can you add it in the readme itself how to use the library?

**Comment by Deepscorn** [comment]
Successfully added in the old way:

**Comment by Innarticles** [comment]
Same problem here: 
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'' finished with non-zero exit value 2

Any solution yet?

**Comment by vipulbansal** [comment]
No mate.

**Comment by Innarticles** [comment]
You can try http://www.jondev.net/articles/Sending_Emails_without_User_Intervention_%28no_Intents%29_in_Android
while we wait for this issue to be resolved.

I still prefer kristijandraca solution.
