### ISSUE TITLE
alwayd Authentication Failed Exception, I've confirmed the username and password

### ISSUE THREAD

**Issue by wdx700** [kristijandraca/BackgroundMailLibrary#7]
01-08 21:35:46.425: W/System.err(23534): javax.mail.AuthenticationFailedException
01-08 21:35:46.425: W/System.err(23534): 	at javax.mail.Service.connect(Service.java:319)
01-08 21:35:46.425: W/System.err(23534): 	at javax.mail.Service.connect(Service.java:169)
01-08 21:35:46.425: W/System.err(23534): 	at javax.mail.Service.connect(Service.java:118)
01-08 21:35:46.425: W/System.err(23534): 	at javax.mail.Transport.send0(Transport.java:188)
01-08 21:35:46.425: W/System.err(23534): 	at javax.mail.Transport.send(Transport.java:118)
01-08 21:35:46.425: W/System.err(23534): 	at com.kristijandraca.backgroundmaillibrary.mail.GmailSender.sendMail(GmailSender.java:77)
01-08 21:35:46.425: W/System.err(23534): 	at com.kristijandraca.backgroundmaillibrary.BackgroundMail$startSendingEmail.doInBackground(BackgroundMail.java:119)
01-08 21:35:46.425: W/System.err(23534): 	at com.kristijandraca.backgroundmaillibrary.BackgroundMail$startSendingEmail.doInBackground(BackgroundMail.java:1)
01-08 21:35:46.425: W/System.err(23534): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
01-08 21:35:46.425: W/System.err(23534): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-08 21:35:46.430: W/System.err(23534): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
01-08 21:35:46.430: W/System.err(23534): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-08 21:35:46.430: W/System.err(23534): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-08 21:35:46.430: W/System.err(23534): 	at java.lang.Thread.run(Thread.java:841)

**Comment by kristijandraca** [comment]
try this
https://github.com/kristijandraca/BackgroundMailLibrary/issues/3#issuecomment-60357918
