### ISSUE TITLE
Which jar to add to the (android) project ?

### ISSUE THREAD

**Issue by yluom** [kristijandraca/BackgroundMailLibrary#8]
Hi, 
I know this seems like a dumb question, but which .jar(s) are we supposed to use in our android project classpath ?

android-support-v4.jar does not provide any BackgroundMail object.

Are we supposed to use backgroundmaillibrary.jar that needs mail.jar that needs activation.jar  that needs additionnal.jar ?

*Adding those 4 jars works, but it seems a bit overkill to add 4 jars to my project only to send a background mail :')*

Alternate question:
I'm using `bm.setFormBody("You will find the new image in attachments.");` to set the text of the mail, but the mail I receive is empty (however the image attachement is attached to the mail). How to fix/debug this ?

Many Thanks :)

**Comment by nlubello** [comment]
Don't add jar as a reference!
Import BackgroundMailLibrary as a Eclipse project.
Make sure if flagged as a project in the properties.
Now open your project properties and in Android tab import the library!
