### ISSUE TITLE
Getting exception when sending Email

### ISSUE THREAD

**Issue by ranjithnair02** [kristijandraca/BackgroundMailLibrary#9]
This is the exception when sending mail:

'com.kristijandraca.backgroundmaillibrary.mail.GmailSender', referenced from method com.kristijandraca.backgroundmaillibrary.BackgroundMail$startSendingEmail.doInBackground
01-19 01:22:21.699: E/MTD.ASD.WindowManagerImpl(15382): ViewRootImpl.setView failed:android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
01-19 01:22:22.219: E/AndroidRuntime(15382): FATAL EXCEPTION: AsyncTask #1
01-19 01:22:22.219: E/AndroidRuntime(15382): java.lang.RuntimeException: An error occured while executing doInBackground()
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at android.os.AsyncTask$3.done(AsyncTask.java:278)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.lang.Thread.run(Thread.java:856)
01-19 01:22:22.219: E/AndroidRuntime(15382): Caused by: java.lang.NoClassDefFoundError: com.kristijandraca.backgroundmaillibrary.mail.GmailSender
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at com.kristijandraca.backgroundmaillibrary.BackgroundMail$startSendingEmail.doInBackground(BackgroundMail.java:111)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at com.kristijandraca.backgroundmaillibrary.BackgroundMail$startSendingEmail.doInBackground(BackgroundMail.java:1)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at android.os.AsyncTask$2.call(AsyncTask.java:264)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
01-19 01:22:22.219: E/AndroidRuntime(15382): 	... 5 more
01-19 01:22:27.939: E/AuthorizationBluetoothService(467): Proximity feature is not enabled.

**Comment by stormj** [comment]
Could you maybe post some of your code here?

**Comment by ranjithnair02** [comment]
The issue was with my code. I am closing the issue.
